### ISSUE TITLE
Add minimal servant example

### ISSUE THREAD

**Issue by anisjonischkeit** [plow-technologies/ocaml-export#25]
I'm really struggling to figure out what I need to do to get this working inside servant. I have tried to follow what is happening in the tests but am just not really getting how to hook up all of the different parts. A minimal servant example would be super helpful.

**Comment by mchaver** [comment]
Thanks for the comment @anisjonischkeit . I agree that in its current state it is not that easy to use and some examples would be helpful. Are you wanting to see a Haskell servant backend with a set of types that gets exported to BuckleScript/ReasonML? I can try to put that together this week.

**Comment by anisjonischkeit** [comment]
Thanks so much for the help, that would be super helpful. Yeah, I was looking for something like https://github.com/mattjbray/servant-elm but for ReasonML. It looks like ocaml-export doesn't currently export functions to do the fetching so if I get the type exporting working I'd probably have a go at doing that.

**Comment by anisjonischkeit** [comment]
Hey @mchaver, did you get a chance to have a look at this?

**Comment by mchaver** [comment]
@anisjonischkeit 
Sorry for the long delay. I finally made an example app. Take a look at the example directory and the readme. Let me know if it makes sense. The build is manually. Sometime in the future I will try to clean it up.

**Comment by anisjonischkeit** [comment]
Hey, thanks heaps for this! I've been on holiday for the past month and so haven't had time to look at this. It's actually looking like I won't need this in the near future as hasura solves most of what I was using the servant backend for. I'm happy for this to be closed and I can reopen this if I work on something else in the future that would need this.

**Comment by mchaver** [comment]
Great, just let me know!
